### PR TITLE
Add licence

### PR DESCRIPTION
**Pull request by mrfishie**
This pull request adds the MIT licence and a small notice on the README about it, as discussed in #64.

Questions before this is pulled:
- Should the disclaimer in the README also be included in the LICENCE file?
- Should we add some licence info on the documentation page? (e.g. at the end)

Thoughts?

### CODE REVIEW

**Comment by rjwut** [comment]
Regarding your questions: I think it's fine as is.

**Comment by mrfishie** [comment]
@chrivers Happy now? ;P

**Comment by chrivers** [comment]
This might be less of a problem with MIT, but normally the license should never be modified. This would in effect create a new license type, with new considerations for compatability, legal precedence, etc.

Since it is legally impossible for us to license or copyright  the protocol itself, I think the Readme notice is just fine

**Comment by mrfishie** [comment]
I was more thinking adding the disclaimer to the top of the LICENCE file, which I don't believe would count as modifying it (just putting some text before it). But if you guys think it's fine as-is, that's all good.

**Comment by chrivers** [comment]
It great now, +1 from here

**Pull request merged**
